### ISSUE TITLE
[venus-message] MySQL has error after upgrade version to v1.10.1 / 將組件升級之後MySQL出現error

### ISSUE THREAD

**Issue by AruXc** [filecoin-project/venus#5821]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus message version 1.10.1+git.61d6c29
```

### 描述 / Describe the Bug

 mysql has error after upgrade version to v1.10.1
![image](https://user-images.githubusercontent.com/34891107/224762032-7fe96fc2-e6f8-48b3-9ad5-7bace991d2bc.png)

### 日志 / Logging Information

```text
2023/03/13 23:04:21 /home/aru/go/pkg/mod/gorm.io/driver/mysql@v1.1.1/migrator.go:83 Error 1138: Invalid use of NULL value
[33. 135ms] [rows:0] ALTER TABLE~addresses' MODIFY COLUMN~gas_over_premium~ decimal(10,2) NOT NULL
2023-03-13T23:04:21.242+0800 INFO main venus-messager_1 10/main.go:381 [Fx] ERROR fx.Invoke(github.com/f
ed from:
github.com/filecoin-project/venus-messager/models.Options
/home/aru/venus-messager_1_10/models/modules.go:31
main.runaction
/home/aru/venus-messager_1_10/main.go:296
github.com/urfave/cli/v2.(*Command).Run
/home/aru/go/pkg/mod/github.com/urfave/cli/v2@v2.16.31command.go:173
github.com/urfave/cli/v2.(*App).RunContext
/home/aru/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:383
github.com/urfave/cli/v2.(*App).Run
/home/aru/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main
/home/aru/venus-messager_1_10/main.go:67
runtime.main /usr/local/go/src/ runtime/proc.go:250
Failed: Error 1138: Invalid use of NULL value
2023-03-13T23:04:21.242+0800 INFO main starting app: Error 1138: Invalid use of NULL value venus-messager_1_10/main.go:381 [Fx] ERROR Failed to start: Error
```

### 重现步骤 / Repo Steps

1.upgrade venus-messager version to v1.10.1
2.start the venus-messager component

**Comment by simlecode** [comment]
无法重现，后续有问题再处理
